# Run at configure and build time; write only when identity changes.
find_package(Git QUIET)
set(hash "unknown")
set(commit "unknown")
set(dirty false)
if(GIT_FOUND)
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --short=7 HEAD
        OUTPUT_VARIABLE hash OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE rc ERROR_QUIET)
    if(NOT rc EQUAL 0)
        set(hash "unknown")
    else()
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse HEAD
            OUTPUT_VARIABLE commit OUTPUT_STRIP_TRAILING_WHITESPACE)
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" diff --quiet HEAD --ignore-submodules=none
            RESULT_VARIABLE changed)
        if(NOT changed EQUAL 0)
            set(dirty true)
        endif()
    endif()
endif()
set(display "${APP_VERSION}+${hash}")
if(dirty)
    string(APPEND display ".d")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(header "#pragma once\n#define NSL_APP_VERSION \"${display}\"\n#define NSL_SEMANTIC_VERSION \"${APP_VERSION}\"\n#define NSL_GIT_COMMIT \"${commit}\"\n")
set(manifest "{\n  \"version\": \"${APP_VERSION}\",\n  \"display_version\": \"${display}\",\n  \"commit\": \"${commit}\",\n  \"dirty\": ${dirty}\n}\n")
foreach(name IN ITEMS build_identity.h build_identity.json)
    if(name MATCHES "\\.h$")
        set(content "${header}")
    else()
        set(content "${manifest}")
    endif()
    set(old "")
    if(EXISTS "${OUTPUT_DIR}/${name}")
        file(READ "${OUTPUT_DIR}/${name}" old)
    endif()
    if(NOT content STREQUAL old)
        file(WRITE "${OUTPUT_DIR}/${name}" "${content}")
    endif()
endforeach()
