if(NOT DEFINED SYMBOL)
    set(SYMBOL nsl_background)
endif()
file(READ "${INPUT}" data HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," data "${data}")
file(WRITE "${OUTPUT}" "#include <stddef.h>\nconst unsigned char ${SYMBOL}[] = {${data}};\nconst size_t ${SYMBOL}_size = sizeof(${SYMBOL});\n")
